### ISSUE TITLE
Username not displayed in RTL

### ISSUE THREAD

**Issue by paul999** [paul999/ajax-shoutbox-ext#40]
See http://www.ajax-shoutbox.com/viewtopic.php?f=5&t=20&p=145#p145

**Comment by Galixte** [comment]
Hi @paul999,

could you take a look, please ?

**Comment by paul999** [comment]
Like said, it will be fixed on the next release.

**Comment by hamidouki** [comment]
i have this probléme http://www.ajax-shoutbox.com/viewtopic.php?f=5&t=20&p=145#p145  too
