### ISSUE TITLE
UCP - Can't change user language and style

### ISSUE THREAD

**Issue by Galixte** [paul999/ajax-shoutbox-ext#42]
Hi,

since i activated this extension, in my UCP i can't to change the language or the style or both.

**Comment by Galixte** [comment]
Hi,

I think it's PHP 5.4 which is the way of this problem. Because, since i have updated my PHP version on my server to PHP 5.5, i don't have this problem anymore.

**Comment by Galixte** [comment]
Hi @paul999,

could you take a look ?

**Comment by nikitasius** [comment]
Confirm this bug on 5.4.4

**Comment by nikitasius** [comment]
and no problem on 5.6.7

**Comment by Galixte** [comment]
Hi, 

before i was on PHP 5.4.38 and since a month ago i'm on PHP 5.5.23.

**Comment by razyr** [comment]
I was testing this chat plugin when initially setting up a new system.  I found that even with the plugin deleted from the server, the bug persisted which prevented the UCP/Board Preferences/Edit Global Settings page from saving.   It not only prevents the user from changing their TZ prefs, it prevents saving options such as "Hide my online status", since they are on the same page in the UCP.

I'm not sure why this plugin needs a separate TZ setting and wouldn't just pull the timezone from the "My Timezone" UCP prefs.

I wound up doing a clean install.   Now the forum is live, I'm reluctant to try it again.  Be nice to eventually add this feature once our site traffic builds.   The chat app is perfect in every other way.

**Comment by paul999** [comment]
There is no timezone setting in this extension, only a date format setting, which is something different ;).

For now the best thing is to upgrade your php, which seems to solve it. In 1.1.0 I will look into fixing it, but as for now I haven't been able to reproduce it, as I don't have a php 5.4 anymore.

**Comment by razyr** [comment]
Sorry, my bad.  I no longer have the plugin installed and was going from memory.  

Setting PHP 5.5 as a prereq isn't very practical in the real world.  5.5 and newer represent less than 10% of the PHP install base.  See http://w3techs.com/technologies/history_details/pl-php/5.  You are eliminating users who run PHPBB in most shared hosting environments or running standard installs of enterprise class linux distros like RHEL 7.

But for this one bug, the plugin works perfectly even on 5.3.

**Comment by paul999** [comment]
For now the solution is, if you want to use that UCP page, to upgrade to php 5.5 (I am not sure the issue happens in 5.3 as well, might not happen there).

If you host is still running 5.3, I would suggest you look for getting a new webhost, as they are running EOL software: http://php.net/eol.php php 5.5 will only be supported untill september this year: http://php.net/supported-versions.php while 5.4 is currently only supported for security issues.

And like I said, for the next major release, it probably will be fixed. For the version which currently is in the queue at phpBB.com it won't be.

**Comment by razyr** [comment]
Thanks Paul.  I'm not defending the use of outdated software, just pointing out that the current system reqs eliminate 90% of the install base.

I'll look forward to the next major release.

**Comment by paul999** [comment]
Can someone confirm that this still happens with 3.1.4?

**Comment by Biscuiticus** [comment]
Running php 5.4, it still happens with 3.1.4.

**Comment by belak** [comment]
I'm running into this now... if you need any help debugging, I can take a look if you give me pointers.

**Comment by paul999** [comment]
Can someone confirm #55  fixes it for now?

**Comment by TimoMF** [comment]
I have the same problem.
But with me the error occurs even under PHP 5.5.9.

**Comment by paul999** [comment]
@TimoMF That more sounds you actually didn't fill in the required fields properly. I am unable to reproduce under that version (It is my development and production branch), and I only have had users reporting it in < 5.5.0 untill now.

For everyone, the fix has been merged. I am not sure if I will be doing another 1.0.x release before the 1.1.x release. For now, you can manually apply manually the fix.

**Comment by stheno** [comment]
This is still happening in php 5.5.9 even with the fix.

**Comment by VicAMMON** [comment]
paul999 , sorry man, but you cannot tell people - change your php version.
I use php 5.4 because I need 5.4. If you cannot get your extension work with 5.4 , this is your problem. If you want to create good extension, it can be used by all supported php versions.

**Comment by paul999** [comment]
I don't see why it is my problem, I can use it fine as I want to, as I keep my php up to date. 
You are not required to use this extension. 5.4 is years old, and nearly unsupported.

**Comment by paul999** [comment]
Closing this issue as it is fixed by #55
