### ISSUE TITLE
Timezone can't be changed

### ISSUE THREAD

**Issue by Geronimoze** [paul999/ajax-shoutbox-ext#43]
Hi, 

I noticed with version 1.0.0-RC1 that there is now way to change the Timezone in UCP. 
If the user wants to set a specific timezone instead of the default, he just can't. 
Of course, I've checked if the issue was from another extension, but no, it's from the shoutbox 1.0.0-RC1 cause it change the whole board timezone. 

I'm testing it to help ;) 

Have a good day, 
Cordialy, 
Geronimo(ze)

**Comment by paul999** [comment]
Duplicate to #42
