### ISSUE TITLE
CSRF can break other pages

### ISSUE THREAD

**Issue by belak** [paul999/ajax-shoutbox-ext#52]
I'm not sure how/if you want to handle this, but in my experiments with the board3 portal plugin, I noticed that this plugin listens for `core.index_modify_page_title` which only works on the index page.

However, if you change that to `core.page_header_after` (so you can include the shoutbox on any page) it starts breaking other forms, such as post creation.

I have no idea why this happens, but it seems that this may be a hurdle for making the board3 portal (issue #47) integration.

**Comment by belak** [comment]
I'm not sure, but this may be an issue with how phpBB handles forms and not an issue with the shoutbox itself.

**Comment by paul999** [comment]
You are trying something which is simply not supported. You really shouldn't run the code on any page, but be specific for which page you want to show it on.

**Comment by belak** [comment]
So, the best method would be to make sure an event fires for the portal and listen for that as well?
EDIT: I've got a temporary hacky solution for now... I'll be interested to see how the portal integration ends up working when done by someone who actually understands this stuff.
