### ISSUE TITLE
[Feature Request] Chat Commands

### ISSUE THREAD

**Issue by ghost** [paul999/ajax-shoutbox-ext#54]
/ban user time (can't see shouts nor post)
/kick user (forces them to reload page to see)
/timeout user time (can see shouts but cannot post)
/prune all (deletes all posts in the shoutbox
/prune user(deletes all shouts by user)
/prune group(deletes all shouts by group)

**Comment by paul999** [comment]
Sorry, this won't be implemented. Version 1.1.0 will have several events what will be adding commands like this possible for 3rdparty extensions.
