### ISSUE TITLE
Support for Comboot

### ISSUE THREAD

**Issue by vico93** [paul999/ajax-shoutbox-ext#76]
Hi all!

Due to immense code differences between this and standard themes (aka. prosilver and subsilver), i request here to add compatibility for @TheZoker 's Comboot theme.

This theme is a responsive based on [Bootstrap](https://github.com/twbs/bootstrap) 3, and its very beautiful, and is even possible to tweak the default look and feel using [bootswatches](https://bootswatch.com/).

The thing is just create a 'comboot' folder in styles folder and add files compatible with bootstrap, javascript and responsive design, like grid system and etc. And instead to use images for icons use [font-awesome](https://fortawesome.github.io/Font-Awesome/). Offline docs of Bootstrap version 3 is [here](https://github.com/AAlakkad/Bootstrap-3-Offline-Docs).

The comboot repo link is [here](https://github.com/ComBoot/ComBoot-3.1). Its private, and if you guys want to do this Zoker can guide you to access it.

Anyway, thanks in advance!

**Comment by paul999** [comment]
You will need to ask the style author to create compitable templates.

**Comment by vico93** [comment]
Sadly he will charge for that. But i understand your position.
